// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tizentest/database/channel.dart';
import 'package:tizentest/database/series_item.dart';
import 'package:tizentest/database/vod_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChannelAdapter());
    registerAdapter(SeriesItemAdapter());
    registerAdapter(VodItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChannelAdapter());
    registerAdapter(SeriesItemAdapter());
    registerAdapter(VodItemAdapter());
  }
}
